pre-commit:
  stage: test
  extends: .docker
  script:
    - set -euo pipefail
    - apk update && apk upgrade
    - apk add --update libc6-compat libstdc++
    - apk add --no-cache shellcheck shfmt pre-commit nodejs npm
    - apk add --no-cache
      --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community hugo
    - npm i -D postcss postcss-cli autoprefixer
    - pre-commit run --verbose --all-files --show-diff-on-failure
  coverage: /total:\s+\(statements\)\s+\d+.\d+%/

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml
secret_detection:
  stage: test
  allow_failure: false
  artifacts:
    when: on_failure
    expire_in: 7 days
    paths:
      - gl-secret-detection-report.json
