---
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_REF_PROTECTED == "true"

stages:
  - test

.docker:
  image: docker:28.1.1
  services:
    - docker:28.1.1-dind
  before_script:
    - set -euo pipefail
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u
      $CI_REGISTRY_USER --password-stdin
    - apk update && apk upgrade
    - apk add --no-cache bash git make
    - export PATH=$PATH:$HOME/go/bin/
    - wget -O go.tgz https://go.dev/dl/go1.24.3.linux-amd64.tar.gz
    - tar -C /usr/local -xzf go.tgz
    - export PATH=$PATH:/usr/local/go/bin
    - go env -w GOPRIVATE=github.com/SlinkyProject/*

pre-commit:
  stage: test
  extends: .docker
  script:
    - set -euo pipefail
    - apk update && apk upgrade
    - apk add --update libc6-compat libstdc++
    - apk add --no-cache shellcheck shfmt pre-commit nodejs npm
    - apk add --no-cache
      --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community hugo
    - npm i -D postcss postcss-cli autoprefixer
    - pre-commit run --verbose --all-files --show-diff-on-failure
  coverage: /total:\s+\(statements\)\s+\d+.\d+%/

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml
secret_detection:
  stage: test
  allow_failure: false
  artifacts:
    when: on_failure
    expire_in: 7 days
    paths:
      - gl-secret-detection-report.json
